name: golang-ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: golangci-lint
        run: |
          docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.64.7 golangci-lint run -v --timeout=3600s
      - name: Run Gosec Security Scanner
        uses: securego/gosec@136f6c00402b11775d4f4a45d5a21e2f6dd99db2 #v2.22.2