name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe #v4.1.0
        with:
          go-version-file: go.mod
      - name: Initialize CodeQL
        uses: github/codeql-action/init@74483a38d39275f33fcff5f35b679b5ca4a26a99 #v2.22.5
        with:
          languages: go
      - name: Run build
        run: go build github.com/Azure/golden
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@74483a38d39275f33fcff5f35b679b5ca4a26a99 #v2.22.5
      - name: Run tests
        run: go test -v github.com/Azure/golden/...
      - name: Run Gosec Security Scanner
        uses: securego/gosec@136f6c00402b11775d4f4a45d5a21e2f6dd99db2 #v2.22.2